name: ci

on:
  push:
    branches: ['**']
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  AppImage:
    name: AppImage-${{ matrix.build_type }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [Release, Debug]
        include:
          - arch: x86_64
            os: ubuntu-22.04
          - arch: arm64
            os: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
